i18n.dictionary.RUSSIAN:
  recommendation: |
    ‚òÄÔ∏è<b>–£–§ –∏–Ω–¥–µ–∫—Å</b>: ${uvi} (${uvi_level})
    üå°Ô∏èÔ∏è<b>–¢–µ–º–ø–µ—Ä–∞—Ç—É—Ä–∞</b>: ${temperature}¬∞C
    üìç<b>–ú–µ—Å—Ç–æ</b>: ${place}
  unknown_place: –ù–µ–∏–∑–≤–µ—Å—Ç–Ω–æ–µ –º–µ—Å—Ç–æ
  harm_low: –ù–∏–∑–∫–∏–π
  harm_moderate: –£–º–µ—Ä–µ–Ω–Ω—ã–π
  harm_high: –í—ã—Å–æ–∫–∏–π
  harm_very_high: –û—á–µ–Ω—å –≤—ã—Å–æ–∫–∏–π
  harm_extreme: –ß—Ä–µ–∑–º–µ—Ä–Ω—ã–π
  subscribe_button: –ü–æ–¥–ø–∏—Å–∞—Ç—å—Å—è
  unsubscribe_button: –û—Ç–ø–∏—Å–∞—Ç—å—Å—è
  cannot_send_location: |
    ‚Äì –¢–µ–ª–µ–≥—Ä–∞–º –¥–ª—è Windows –Ω–µ –ø–æ–∑–≤–æ–ª—è–µ—Ç –æ—Ç–ø—Ä–∞–≤–∏—Ç—å –≥–µ–æ–ª–æ–∫–∞—Ü–∏—é.
    ‚Äì –ß—Ç–æ–±—ã –æ—Ç–ø—Ä–∞–≤–∏—Ç—å –≥–µ–æ–ª–æ–∫–∞—Ü–∏—é –≤ macOS, –Ω–∞–∂–º–∏—Ç–µ –∏–∫–æ–Ω–∫—É –≤ –≤–∏–¥–µ —Å–∫—Ä–µ–ø–∫–∏ üìé –≤–æ–∑–ª–µ –ø–æ–ª—è –≤–≤–æ–¥–∞ —Ç–µ–∫—Å—Ç–∞. –ö–Ω–æ–ø–∫–∞ –æ—Ç–ø—Ä–∞–≤–∫–∏ –∏–∑ –±–æ—Ç–∞ –º–æ–∂–µ—Ç –Ω–µ —Ä–∞–±–æ—Ç–∞—Ç—å.
    –ü–æ–∂–∞–ª—É–π—Å—Ç–∞, –æ—Ç–ø—Ä–∞–≤—å—Ç–µ –≥–µ–æ–ª–æ–∫–∞—Ü–∏—é —Å –ø–æ–º–æ—â—å—é —Ç–µ–ª–µ—Ñ–æ–Ω–∞.
  cannot_send_location_button: –£ –º–µ–Ω—è –Ω–µ –ø–æ–ª—É—á–∞–µ—Ç—Å—è –æ—Ç–ø—Ä–∞–≤–∏—Ç—å –ª–æ–∫–∞—Ü–∏—é
  settings_menu_title: –ß—Ç–æ —Ö–æ—Ç–∏—Ç–µ —Å–¥–µ–ª–∞—Ç—å?
  subscribe_reply: –£—Ä–∞! –ú—ã –±—É–¥–µ–º –æ–ø–æ–≤–µ—â–∞—Ç—å –≤–∞—Å –æ–± –∏–∑–º–µ–Ω–µ–Ω–∏–∏ –£–§-–∏–Ω–¥–µ–∫—Å–∞!
  unsubscribe_reply: –í—ã –æ—Ç–ø–∏—Å–∞–ª–∏—Å—å –æ—Ç —É–≤–µ–¥–æ–º–ª–µ–Ω–∏–π üò™ –í–æ–∑–≤—Ä–∞—â–∞–π—Ç–µ—Å—å —Å–∫–æ—Ä–µ–µ, —á—Ç–æ–±—ã –æ—Å—Ç–∞–≤–∞—Ç—å—Å—è –∑–∞—â–∏—â–µ–Ω–Ω—ã–º –æ—Ç —Å–æ–ª–Ω—Ü–∞.
  init_message: –ü–æ–∂–∞–ª—É–π—Å—Ç–∞, –æ—Ç–ø—Ä–∞–≤—å—Ç–µ –≥–µ–æ–ª–æ–∫–∞—Ü–∏—é.
  main_menu: –î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å! –ü–æ–∂–∞–ª—É–π—Å—Ç–∞, –æ—Ç–ø—Ä–∞–≤—å—Ç–µ –≥–µ–æ–ª–æ–∫–∞—Ü–∏—é.
