i18n.dictionary:
  en:
    recommendation: |
      â˜€ï¸ Ğ£Ğ¤ Ğ¸Ğ½Ğ´ĞµĞºÑ: {uvi} ({uvi_level})
      ğŸŒ¡ï¸ï¸ Ğ¢ĞµĞ¼Ğ¿ĞµÑ€Ğ°Ñ‚ÑƒÑ€Ğ°: {temperature}Â°C
      ğŸ“ ĞœĞµÑÑ‚Ğ¾: {place}
      ğŸ¤– Ğ ĞµĞºĞ¾Ğ¼ĞµĞ½Ğ´Ğ°Ñ†Ğ¸Ñ Ğ˜Ğ˜: {ai_recommendation}
