i18n.dictionary:
  RUSSIAN:
    recommendation: |
      โ๏ธ<b>ะฃะค ะธะฝะดะตะบั</b>: ${uvi} (${uvi_level})
      ๐ก๏ธ๏ธ<b>ะขะตะผะฟะตัะฐัััะฐ</b>: ${temperature}ยฐC
      ๐<b>ะะตััะพ</b>: ${place}
      
      ๐ค<b>ะะตะบะพะผะตะฝะดะฐัะธั ะะ</b>: ${ai_recommendation}
