i18n.dictionary:
  ENGLISH:
    recommendation: |
      â˜€ï¸ <b>UV index:</b> ${uvi} (${uvi_level})
      ğŸŒ¡ï¸ï¸ <b>Temperature:</b> ${temperature}Â°C
      ğŸ“ <b>Place:</b> ${place}

      ğŸ¤– <b>AI recommendation:</b> ${ai_recommendation}
