i18n.dictionary:
  english:
    recommendation: |
      â˜€ï¸ UV index: {uvi} ({uvi_level})
      ğŸŒ¡ï¸ï¸ Temperature: {temperature}Â°C
      ğŸ“ Place: {place}
      ğŸ¤– AI recommendation: {ai_recommendation}
