i18n.dictionary.ENGLISH:
  recommendation: |
    â˜€ï¸ <b>UV index:</b> ${uvi} (${uvi_level})
    ğŸŒ¡ï¸ï¸ <b>Temperature:</b> ${temperature}Â°C
    ğŸ“ <b>Place:</b> ${place}

    ğŸ¤– <b>AI recommendation:</b> ${ai_recommendation}
  harm_low: Low
  harm_moderate: Moderate
  harm_high: High
  harm_very_high: Very high
  harm_extreme: Extreme
  subscribe_button: Subscribe
  unsubscribe_button: Unsubscribe
  cannot_send_location: |
    â€“ In Telegram for Windows, it is not possible to send a location.
    â€“ To send a location in macOS, manually send it using the button with a paperclip ğŸ“ icon next to the message input field. The button in the bot might not work.
    Please use a mobile device to send a location.
  cannot_send_location_button: I can't send location
  settings_menu_title: What do you want to do?
  subscribe_reply: Hooray! We will now send notifications when the UV index changes!
  unsubscribe_reply: You have unsubscribed from notifications ğŸ˜ª Come back soon to always stay protected from the sun.
  init_message: |
    ğŸ‘‹ Please send your location ğŸ‘‡ğŸ“ Press the button in the menu.
    
    ğŸ¤·â€â™€ï¸If nothing happened or you can't see the button,
    press paperclip ğŸ“ button next to the message field in Telegram and choose "Location".
    
    _______________________________
    
    ğŸ‘‹ ĞŸĞ¾Ğ¶Ğ°Ğ»ÑƒĞ¹ÑÑ‚Ğ°, Ğ¾Ñ‚Ğ¿Ñ€Ğ°Ğ²ÑŒÑ‚Ğµ Ğ³ĞµĞ¾Ğ»Ğ¾ĞºĞ°Ñ†Ğ¸Ñ ğŸ‘‡ğŸ“ ĞĞ°Ğ¶Ğ¼Ğ¸Ñ‚Ğµ ĞºĞ½Ğ¾Ğ¿ĞºÑƒ Ğ² Ğ¼ĞµĞ½Ñ.
    
    ğŸ¤·â€â™€ï¸Ğ•ÑĞ»Ğ¸ Ğ½Ğ¸Ñ‡ĞµĞ³Ğ¾ Ğ½Ğµ Ğ¿Ñ€Ğ¾Ğ¸Ğ·Ğ¾ÑˆĞ»Ğ¾ Ğ¸Ğ»Ğ¸ ĞºĞ½Ğ¾Ğ¿ĞºÑƒ Ğ½Ğµ Ğ²Ğ¸Ğ´Ğ½Ğ¾,
    Ğ½Ğ°Ğ¶Ğ¼Ğ¸Ñ‚Ğµ Ğ½Ğ° Ğ¸ĞºĞ¾Ğ½ĞºÑƒ ğŸ“ ÑĞºÑ€ĞµĞ¿ĞºĞ¸ Ğ²Ğ¾Ğ·Ğ»Ğµ Ğ¿Ğ¾Ğ»Ñ Ğ²Ğ²Ğ¾Ğ´Ğ° ÑĞ¾Ğ¾Ğ±Ñ‰ĞµĞ½Ğ¸Ñ Ğ¸ Ğ²Ñ‹Ğ±ĞµÑ€Ğ¸Ñ‚Ğµ "Ğ“ĞµĞ¾Ğ¿Ğ¾Ğ·Ğ¸Ñ†Ğ¸Ñ".
    
    ğŸ‡¬ğŸ‡§ Ğ¯Ğ·Ñ‹Ğº Ğ¼Ğ¾Ğ¶Ğ½Ğ¾ Ğ¸Ğ·Ğ¼ĞµĞ½Ğ¸Ñ‚ÑŒ Ğ² Ğ½Ğ°ÑÑ‚Ñ€Ğ¾Ğ¹ĞºĞ°Ñ… âœ¨
  main_menu: Welcome! Please send your location.
